/**
 * @file plotter_protocol.h
 * @brief PlotterApp Communication Protocol Reference
 *
 * This header documents the data format and protocol used for
 * communicating with PlotterApp via Serial, MQTT, WiFi, or other interfaces.
 *
 * The actual implementation is in plotter.h and plotter.cpp.
 * This file serves as protocol documentation and reference.
 *
 * @version 4.0
 * @date 2025-12-11
 */

#ifndef PLOTTER_PROTOCOL_H
#define PLOTTER_PROTOCOL_H

#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

/**
 * @brief PlotterApp Communication Protocol
 *
 * The PlotterApp expects data in JSON format with the following structure:
 *
 * Format 1 - With timestamp (recommended):
 * {"id":0,"value":123.456789,"timestamp":1.234567}
 *
 * Format 2 - Without timestamp (auto-generated by PlotterApp):
 * {"id":0,"value":123.456789}
 *
 * Format 3 - Plain number (fallback, single channel only):
 * 123.456789
 *
 * All formats must end with a newline character (\n).
 */

/**
 * @brief Data point structure
 *
 * Represents a single measurement point for plotting.
 *
 * @note ID must be in range 0-255
 * @note Each ID represents a different plot line
 * @note Timestamp is optional (set to 0.0f or omit from JSON if not needed)
 */
typedef struct {
    uint8_t id;          ///< Channel/Line ID (0-255)
    float value;         ///< Y-axis value (measurement)
    float timestamp;     ///< X-axis value in seconds (optional)
} PlotDataPoint;

/**
 * @brief Protocol Constants
 */
#define PLOTTER_MIN_ID 0           ///< Minimum valid channel ID
#define PLOTTER_MAX_ID 255         ///< Maximum valid channel ID
#define PLOTTER_PRECISION 6        ///< Default decimal precision for float values
#define PLOTTER_BUFFER_SIZE 64     ///< Recommended buffer size for formatted data

/**
 * @brief JSON Field Names
 *
 * These are the exact field names expected by PlotterApp:
 * - "id": Channel identifier (integer 0-255)
 * - "value": Measurement value (float)
 * - "timestamp": Optional timestamp in seconds (float)
 */
#define PLOTTER_FIELD_ID "id"
#define PLOTTER_FIELD_VALUE "value"
#define PLOTTER_FIELD_TIMESTAMP "timestamp"

/**
 * @brief Protocol Examples
 *
 * Example 1: Single sensor with timestamp
 * {"id":0,"value":25.500000,"timestamp":1.234567}
 *
 * Example 2: Multiple sensors with same timestamp
 * {"id":0,"value":25.5,"timestamp":1.234}
 * {"id":1,"value":60.2,"timestamp":1.234}
 * {"id":2,"value":1013.25,"timestamp":1.234}
 *
 * Example 3: Single sensor without timestamp (auto-generated)
 * {"id":0,"value":25.5}
 *
 * Example 4: Plain number (legacy, single channel only)
 * 25.5
 */

/**
 * @brief Data Format Requirements
 *
 * 1. JSON Structure:
 *    - Must be valid JSON object: {"key":value,...}
 *    - Field names must be lowercase
 *    - No spaces after colons (recommended for minimal size)
 *    - Must end with newline (\n)
 *
 * 2. Field Types:
 *    - "id": Integer (0-255)
 *    - "value": Float (6 decimal places recommended)
 *    - "timestamp": Float in seconds (6 decimal places recommended)
 *
 * 3. Float Formatting:
 *    - Use %.6f for consistent precision
 *    - Timestamp in seconds (not milliseconds!)
 *    - Convert milliseconds to seconds: timestamp = ms / 1000.0
 *
 * 4. Newline Termination:
 *    - Every message must end with \n
 *    - PlotterApp uses line-based parsing
 *
 * 5. Character Encoding:
 *    - UTF-8 encoding
 *    - ASCII subset recommended for best compatibility
 */

/**
 * @brief Timestamp Handling
 *
 * Timestamps should be in seconds (float), not milliseconds!
 *
 * Best practice:
 * 1. Set start time once: plotter.setStartTime(millis())
 * 2. Send relative timestamps: plotter.send(id, value, millis())
 *    The Plotter class automatically converts ms to seconds
 *
 * Manual calculation:
 * float timestamp = (currentTime_ms - startTime_ms) / 1000.0f;
 *
 * If timestamps are omitted:
 * - PlotterApp will auto-generate based on arrival time
 * - Less accurate for burst data or delayed transmission
 */

/**
 * @brief Channel ID Usage
 *
 * - Valid range: 0-255 (uint8_t)
 * - Each ID appears as separate line in PlotterApp
 * - Use consistent IDs for the same sensor/measurement
 * - Example mapping:
 *   ID 0: Temperature
 *   ID 1: Humidity
 *   ID 2: Pressure
 *   ID 3: Light level
 */

/**
 * @brief Error Handling
 *
 * PlotterApp will ignore or warn on:
 * - Invalid JSON syntax
 * - Missing required fields ("id" or "value")
 * - ID out of range (not 0-255)
 * - Non-numeric values
 * - Invalid UTF-8 encoding
 *
 * The Python backend logs warnings for debugging.
 */

/**
 * @brief Implementation Reference
 *
 * For actual implementation, use the Plotter class from plotter.h:
 *
 * @code
 * #include <plotter.h>
 *
 * Plotter plotter(Serial);
 *
 * void setup() {
 *     Serial.begin(115200);
 *     plotter.setStartTime(millis());
 * }
 *
 * void loop() {
 *     float value = readSensor();
 *     plotter.send(0, value, millis());
 *     delay(100);
 * }
 * @endcode
 *
 * See plotter.h for complete API documentation.
 */

#ifdef __cplusplus
}
#endif

#endif // PLOTTER_PROTOCOL_H
