/**
 * @file main.cpp
 * @brief STM32 UART example using Plotter class
 *
 * Uses UART to stream sensor data to PlotterApp via USB-Serial adapter.
 * Generated with STM32CubeMX with USART peripheral enabled.
 *
 * @version 4.0
 * @date 2025-12-11
 */

#include "main.h"
#include "../../common/plotter.h"
#include "../../common/plotter_stm32.h"
#include <string.h>

#define SAMPLE_RATE_MS 50  // 20 Hz

UART_HandleTypeDef huart2;
ADC_HandleTypeDef hadc1;

// Create UART stream and plotter
UARTStream uartStream(&huart2);
Plotter plotter(uartStream);

uint32_t lastSample = 0;

void SystemClock_Config(void);
static void MX_GPIO_Init(void);
static void MX_USART2_UART_Init(void);
static void MX_ADC1_Init(void);

int main(void) {
    HAL_Init();
    SystemClock_Config();
    MX_GPIO_Init();
    MX_USART2_UART_Init();
    MX_ADC1_Init();

    // Set start time for plotter
    plotter.setStartTime(HAL_GetTick());

    // Send startup message
    const char* msg = "# STM32 UART PlotterApp Example\r\n";
    HAL_UART_Transmit(&huart2, (uint8_t*)msg, strlen(msg), 100);

    while (1) {
        uint32_t currentTime = HAL_GetTick();

        if (currentTime - lastSample >= SAMPLE_RATE_MS) {
            lastSample = currentTime;

            // Read ADC
            HAL_ADC_Start(&hadc1);
            if (HAL_ADC_PollForConversion(&hadc1, 10) == HAL_OK) {
                uint32_t rawValue = HAL_ADC_GetValue(&hadc1);
                float voltage = (rawValue / 4095.0f) * 3.3f;

                // Send data point (channel 0)
                plotter.send(0, voltage, currentTime);
            }
            HAL_ADC_Stop(&hadc1);
        }

        // Small delay to prevent blocking
        HAL_Delay(1);
    }
}

void SystemClock_Config(void) {
    // Configure system clock (generated by CubeMX)
    // This is a placeholder - use your actual clock configuration
}

static void MX_USART2_UART_Init(void) {
    // Configure UART (generated by CubeMX)
    // This is a placeholder - use your actual UART configuration
    // Typical settings: 115200 baud, 8N1
}

static void MX_ADC1_Init(void) {
    // Configure ADC (generated by CubeMX)
    // This is a placeholder - use your actual ADC configuration
}

static void MX_GPIO_Init(void) {
    // Configure GPIO (generated by CubeMX)
    // This is a placeholder - use your actual GPIO configuration
}

void Error_Handler(void) {
    __disable_irq();
    while (1) {
        // Error state
    }
}
